openapi: 3.0.0
info:
  title: Blockchain Server API
  version: 1.0.0
paths:
  /ticket/all:
    get:
      summary: create new user wallet
      responses:
        '200':
          description: new wallet
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
components:
  schemas:
    Ticket:
      type: object
      properties:
        ticket_id:
          type: string
        name:
          type: string
        description:
          type: string
        owner_address:
          type: string
        price:
          type: string
        image_url:
          type: string
      required:
        - ticket_id
        - name
        - description
        - owner_address
        - price
        - image_url