openapi: 3.0.0
info:
  title: Wallet Server API
  version: 1.0.0
paths:
  /wallet:
    post:
      summary: create new user wallet
      responses:
        '200':
          description: new wallet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
  /transaction:
    post:
      summary: send
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sender_private_key:
                  type: string
                sender_blockchain_address:
                  type: string
                recipient_blockchain_address:
                  type: string
                sender_public_key:
                  type: string
                value:
                  type: string
              required:
                - sender_private_key
                - sender_blockchain_address
                - recipient_blockchain_address
                - sender_public_key
                - value
      responses:
        '200':
          description: send success
        '400':
          description: send fail
  /ticket/all:
    get:
      summary: get all tickets
      responses:
        '200':
          description: tickets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
components:
  schemas:
    Wallet:
      type: object
      properties:
        private_key:
          type: string
        public_key:
          type: string
        blockchain_address:
          type: string
      required:
        - private_key
        - public_key
        - blockchain_address
    Ticket:
      type: object
      properties:
        ticket_id:
          type: int
        name:
          type: string
        description:
          type: string
        owner_address:
          type: string
        price:
          type: int
        image_url:
          type: string
      required:
        - ticket_id
        - name
        - description
        - owner_address
        - price
        - image_url