openapi: 3.0.0
info:
  title: Blockchain Transactions API
  version: 1.0.0
paths:
  /projects:
    get:
      summary: Get all projects
      responses:
        '200':
          description: A list of pending transactions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    description: The list of projects.
                    items:
                      $ref: '#/components/schemas/Project'
  /fund:
    post:
      summary: Send BTC from user wallet to project wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  description: User wallet address
                to:
                  type: string
                  description: Project wallet address
              required:
                - from
                - to
      responses:
        '200':
          description: On success
        '400':
          description: On failure
components:
  schemas:
    Project:
      type: object
      properties:
        project_id:
          type: string
        project_title:
          type: string
        image_base64:
          type: string
